set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CXX_FLAGS "/std:c++latest -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_ITERATOR_DEBUG_LEVEL=0 -DBOOST_SPIRIT_THREADSAFE -DBOOST_USE_WINAPI_VERSION=0x0602")
set(VCPKG_C_FLAGS "")

set(VCPKG_CMAKE_CONFIGURE_OPTIONS 
    "-DCMAKE_CXX_STANDARD=23"
    "-DCMAKE_CXX_STANDARD_REQUIRED=ON"
    "-DCMAKE_CXX_EXTENSIONS=OFF"
)